[font]
normal = { family = "FiraCode Nerd Font", style = "Retina" }
size = 14

[scrolling]
history = 100000

[window]
blur = true
decorations = "buttonless"
# opacity = 0.90
option_as_alt = "both"
padding = { x = 5, y = 7 }

[general]
import = [
    "~/.config/alacritty/themes/themes/tokyonight-night.toml"
]

[terminal]
shell = "/opt/homebrew/bin/nu"
